spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true

sendgrid.api-key=${SENDGRID_API_KEY}

jwt.secret=${JWT_SECRET:ThisIsADefaultSecretKeyForDev32B}
jwt.expiration-ms=86400000