spring.data.mongodb.uri=mongodb+srv://egoldfar_db:Le-7Rox123!MongoDB@e-learning.ch6ivtb.mongodb.net/elearning?retryWrites=true&w=majority&appName=E-learning
spring.data.mongodb.auto-index-creation=true

sendgrid.api-key=PLACEHOLDER_SENDGRID_KEY